#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm lint-staged || exit 1

if ! git diff --cached --name-only --diff-filter=ACM | xargs -I{} -r secretlint "{}"; then
  echo "🚫 Secretlint found potential secrets in staged files."
  exit 1
fi
